# This rule is not used by the project todo-operator itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants full permissions ('*') over task.example.com.
# This role is intended for users authorized to modify roles and bindings within the cluster,
# enabling them to delegate specific permissions to other users or groups as needed.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: todo-operator
    app.kubernetes.io/managed-by: kustomize
  name: todo-admin-role
rules:
- apiGroups:
  - task.example.com
  resources:
  - todoes
  verbs:
  - '*'
- apiGroups:
  - task.example.com
  resources:
  - todoes/status
  verbs:
  - get
